plugins {
    id "com.android.application"
}

configurations.configureEach {
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
}

android {
    namespace "de.astra.pulse"
    compileSdk 35

    defaultConfig {
        applicationId "de.astra.pulse"
        minSdk 23
        targetSdk 35
        versionCode 15
        versionName "2.4"
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.biometric:biometric:1.1.0"
}
